namespace:
  create: true
  name: dev-frontend

serviceAccount:
  create: true

image:
  repository: us-central1-docker.pkg.dev/eks-terraform/dev-repo/frontend-web
  tag: "v1.2.0"

replicaCount: 1

service:
  enabled: true
  port: 80
  targetPort: 3000

persistence:
  enabled: false # No file storage needed for static UI frontend

env:
  - name: NEXT_PUBLIC_API_URL
    value: "http://backend-api.dev-backend.svc.cluster.local"

probes:
  startup:
    enabled: false
  readiness:
    enabled: true
    path: /
    port: 3000
  liveness:
    enabled: true
    path: /
    port: 3000

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi