{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "eks-generic-app.fullname" . }}
  labels:
    {{- include "eks-generic-app.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  target:
    name: {{ include "eks-generic-app.secretName" . }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.remoteRef }}
{{- end }}