{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eks-generic-app.fullname" . }}
  labels:
    {{- include "eks-generic-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "eks-generic-app.selectorLabels" . | nindent 6 }}
{{- end }}
