apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "eks-test-app.fullname" . }}-efs-pv
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.efsFileSystemId }}
