apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "eks-test-app.fullname" . }}-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  volumeName: {{ include "eks-test-app.fullname" . }}-efs-pv
